version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  gradio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '7860:7860'
    depends_on:
      - redis


volumes:
  cache:
    driver: local